
TaskStatement.create(:onet_id => 1, :body => "Operate telephone switchboard to answer, screen, or forward calls, providing information, taking messages, or scheduling appointments.")
TaskStatement.create(:onet_id => 2, :body => "Greet persons entering establishment, determine nature and purpose of visit, and direct or escort them to specific destinations.")
TaskStatement.create(:onet_id => 3, :body => "Schedule appointments and maintain and update appointment calendars.")
TaskStatement.create(:onet_id => 4, :body => "Hear and resolve complaints from customers or the public.")
TaskStatement.create(:onet_id => 5, :body => "File and maintain records.")
TaskStatement.create(:onet_id => 6, :body => "Receive payment and record receipts for services.")
TaskStatement.create(:onet_id => 7, :body => "Perform administrative support tasks, such as proofreading, transcribing handwritten information, or operating calculators or computers to work with pay records, invoices, balance sheets, or other documents.")
TaskStatement.create(:onet_id => 8, :body => "Transmit information or documents to customers, using computer, mail, or facsimile machine.")
TaskStatement.create(:onet_id => 9, :body => "Analyze data to determine answers to questions from customers or members of the public.")
TaskStatement.create(:onet_id => 10, :body => "Collect, sort, distribute, or prepare mail, messages, or courier deliveries.")



#create a receptionist
j=JobBenchmark.create(:title => "Receptionist", :description => "Answer inquiries and provide information to the general public, customers, visitors, and other interested parties regarding activities conducted at establishment and location of departments, offices, and employees within the organization.")
j.assessment_discs<<AssessmentDisc.find_by_name("Influencer")
j.assessment_discs<<AssessmentDisc.find_by_name("Sociable")
j.assessment_values<<AssessmentValue.find_by_name("Social")
j.assessment_values<<AssessmentValue.find_by_name("Traditional")
j.assessment_values<<AssessmentValue.find_by_name("Economic")
j.assessment_skills<<AssessmentSkill.find_by_name("Customer Service")
j.assessment_skills<<AssessmentSkill.find_by_name("Diplomacy")
j.assessment_skills<<AssessmentSkill.find_by_name("Interpersonal Skills")
j.assessment_skills<<AssessmentSkill.find_by_name("Planning and Organizing")
j.assessment_skills<<AssessmentSkill.find_by_name("Written Communication")
j.task_statements<<TaskStatement.find(1)
j.task_statements<<TaskStatement.find(2)
j.task_statements<<TaskStatement.find(3)
j.task_statements<<TaskStatement.find(4)
j.task_statements<<TaskStatement.find(5)
j.task_statements<<TaskStatement.find(6)
j.task_statements<<TaskStatement.find(7)
j.task_statements<<TaskStatement.find(8)
j.task_statements<<TaskStatement.find(9)
j.task_statements<<TaskStatement.find(10)

#create comms questions
d=AssessmentDisc.find(1)
d.comms_questions<<CommsQuestion.create(:body => "Focus on the task")
d.comms_questions<<CommsQuestion.create(:body => "Talk about expected results")
d.comms_questions<<CommsQuestion.create(:body => "Be businesslike and factual")
d.comms_questions<<CommsQuestion.create(:body => "Provide concise, precise, and organized information")
d.comms_questions<<CommsQuestion.create(:body => "Discuss and answer “what” questions")
d.comms_questions<<CommsQuestion.create(:body => "Argue facts, not feelings")
d.comms_questions<<CommsQuestion.create(:body => "Don’t waste time")
d.comms_questions<<CommsQuestion.create(:body => "Don’t argue details")
d.comms_questions<<CommsQuestion.create(:body => "Provide options.")
d.comms_questions<<CommsQuestion.create(:body => "Don't try to control the conversation")
d.comms_questions<<CommsQuestion.create(:body => "Don't ask unfocused personal questions")
d.comms_questions<<CommsQuestion.create(:body => "Don't put him/her in a corner with no options")

d=AssessmentDisc.find(2)
d.comms_questions<<CommsQuestion.create(:body => "Focus on developing a relationship")
d.comms_questions<<CommsQuestion.create(:body => "Try to show how your ideas will improve his or her image")
d.comms_questions<<CommsQuestion.create(:body => "Be enthusiastic, open, and responsive")
d.comms_questions<<CommsQuestion.create(:body => "Relate to the need to share information, stories, and experience")
d.comms_questions<<CommsQuestion.create(:body => "Be forthcoming and willing to talk")
d.comms_questions<<CommsQuestion.create(:body => "Ask and answer “who” questions")
d.comms_questions<<CommsQuestion.create(:body => "Remember to be warm and approachable at all times")
d.comms_questions<<CommsQuestion.create(:body => "Work to minimize his or her direct involvement with details or personal conflicts.")
d.comms_questions<<CommsQuestion.create(:body => "Point out their personal accomplishments")
d.comms_questions<<CommsQuestion.create(:body => "Don't push them for too many details")
d.comms_questions<<CommsQuestion.create(:body => "Don't be dismissive of their ideas")
d.comms_questions<<CommsQuestion.create(:body => "Don't shut down conversation")

d=AssessmentDisc.find(3)
d.comms_questions<<CommsQuestion.create(:body => "Show that you support them")
d.comms_questions<<CommsQuestion.create(:body => "Emphasize personal, one on one service")
d.comms_questions<<CommsQuestion.create(:body => "During conflict, stress that this does not affect the quality of the relationship")
d.comms_questions<<CommsQuestion.create(:body => "Be relaxed and agreeable")
d.comms_questions<<CommsQuestion.create(:body => "Be logical and systematic")
d.comms_questions<<CommsQuestion.create(:body => "Create a plan with written guidelines")
d.comms_questions<<CommsQuestion.create(:body => "Be prepared to answer “why” questions")
d.comms_questions<<CommsQuestion.create(:body => "Be predictable")
d.comms_questions<<CommsQuestion.create(:body => "Don't dismiss questions about 'why'")
d.comms_questions<<CommsQuestion.create(:body => "Don't focus too closely on the tasks")
d.comms_questions<<CommsQuestion.create(:body => "Don't be emotional and unpredictable")
d.comms_questions<<CommsQuestion.create(:body => "Don't show that you dislike them")

d=AssessmentDisc.find(4)
d.comms_questions<<CommsQuestion.create(:body => "Be systematic, thorough, deliberate, and precise")
d.comms_questions<<CommsQuestion.create(:body => "Focus on the task")
d.comms_questions<<CommsQuestion.create(:body => "Be prepared to answer many “how” questions")
d.comms_questions<<CommsQuestion.create(:body => "Don’t get too personal")
d.comms_questions<<CommsQuestion.create(:body => "Recognize and acknowledge the need to be accurate and logical")
d.comms_questions<<CommsQuestion.create(:body => "Expect to repeat yourself")
d.comms_questions<<CommsQuestion.create(:body => "Allow time for evaluation")
d.comms_questions<<CommsQuestion.create(:body => "Use lots of evidence")
d.comms_questions<<CommsQuestion.create(:body => "Don't be too high level or vague")
d.comms_questions<<CommsQuestion.create(:body => "Don't rush decisions")
d.comms_questions<<CommsQuestion.create(:body => "Don't ask too many personal questions")
d.comms_questions<<CommsQuestion.create(:body => "Don't brush off details and accuracy")